### ISSUE TITLE
Depurate unnecessary files and code

### ISSUE THREAD

**Issue by cptanalatriste** [alekosomegas/robot-assisted-evacuation#3]
Some files are not needed, and they should be removed. For example, 
- `v2.11.1.nlogo` and others in `src`
- The `efg` folder

Also, there's some commented code. It should be removed. For example:
- Lines 70-72 on `abm_analysis.py`
- Lines 54-59 on `abm_results_analysis.py`

**Comment by kangkelidis** [comment]
Removed the impact folder and src from the docker directory and modified dockerfile. Netlogo model and related files are inside the core package (perhaps it should not be there if we expect users to modify the model?).
