### ISSUE TITLE
Distinguish between Artifiact files and Example Files

### ISSUE THREAD

**Issue by cptanalatriste** [alekosomegas/robot-assisted-evacuation#6]
First, fix the typo on `adptation_strategies.py`.

Given that `adptation_strategies.py` is our example scenario for demonstrating the artifact, they should be placed somewhere different, like a `examples` folder. And in this folder, place a `README` describing the example at a high-level (detailed description is for the paper).

The same happens with `start.py`, if it is a sample `start.py`, it should be on an `examples`folder.

Also, please consider putting all the artefact files that the user shouldn't modify (`abm_analysys.py`, `survivor.py`, `utils.py` etc) in their own package, so users can import these types when developing their agents.

Nice to have: Publish this package on PyPi.

**Comment by kangkelidis** [comment]
Typo fixed.

Files that the user should not modify are now in the **_core_** package. Which also includes `example.py`,  containing the example scenarios. The user can modify `start.py` to choose between running scenarios defined in: 

- `config.json`, 
- `example.py` 
- or create new `Scenario` objects elsewhere.

User defined and example adaptation strategies should be saved in the **_strategies_** folder. The `on_contact.py` module will search the **_strategies_** folder for the strategy defined in the `Scenario` .
